# -*- coding: utf-8 -*-
__version__ = '0.1.0'
"""
/***************************************************************************
 smart_map
                                 A QGIS plugin
 Interpolation using Kriging and Machine Learning and generate Management Zones for a set of soil samples
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-08-15
        copyright            : (C) 2018 by Gustavo Willam Pereira (IFSUDESTE-MG)/Domingos Sárvio Magalhães Valente (UFV)/Daniel Marçal de Queiroz (UFV)/Andre Luiz de Freitas Coelho (UFV)/Sandro Manuel Carmelino Hurtado (UFU)
        email                : gustavowillam@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load smart_map class from file smart_map.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Smart_Map import smart_map
    return smart_map(iface)
